const HEADER_HEIGHT = 64 + 48 + 48;
const CONTENT_WIDTH = 192 + 512;
const ROPE_RIGHT_ANCHOR_OFFSETS = [182, 0, -25];
const LANTERN_ANCHOR_OFFSETS = [[-CONTENT_WIDTH/2 + 72 - 5, -5],
    [-CONTENT_WIDTH/2 + 12, 48],
    [-CONTENT_WIDTH/2 + 72 + 5, 144]];
const LANTERN_OFFSET = 12;
const LANTERN_SIZES = [[116, 85], [66, 107], [62, 122]];
const GLOW_SIZES = [[288, 255], [251, 278], [262, 322]];
const GLOW_RADIUS = 100;
const NUM_ITERATIONS = 15;
const GRAVITY = 0.5;
const MOUSE_ATTRACTOR_STRENGTH = 0.25;
const MOUSE_ATTRACTOR_RADIUS = 100;
const SEGMENT_LENGTH = 20;
const ROPE_MASS = 1;

export {
    HEADER_HEIGHT,
    CONTENT_WIDTH,
    ROPE_RIGHT_ANCHOR_OFFSETS,
    LANTERN_ANCHOR_OFFSETS,
    LANTERN_OFFSET,
    LANTERN_SIZES,
    GLOW_RADIUS,
    GLOW_SIZES,
    NUM_ITERATIONS,
    GRAVITY,
    MOUSE_ATTRACTOR_STRENGTH,
    MOUSE_ATTRACTOR_RADIUS,
    SEGMENT_LENGTH,
    ROPE_MASS};